---
title: "Introduction to Quantitative Research Methods"
subtitle: "Descriptive and inferential statistics"
format:
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: mysite/www/AU_CDC_Logo.png
resources:
  - IntroQuant.pdf
editor: visual
---

## Objectives

-   Overview of quantitative data 
-   Descriptive statistics
-   Hypothesis testing
-   Linear regression
-   Logistic regression

# Quantitative data

## Types of quantitative data

::: {.incremental}
- Categorical data
  - Qualitative data
  - Uses numbers as labels for categories
  - Ordered/Unordered
  - No meaningful arithmatic operations
- Numeric data
  - Quantiative data
  - Measurement
  - Discrete/Continuous
:::

## Categorical data

::: {.incremental}
- Nominal data
  - Unordered
  - Survived = 1, Died = 0 
  - Female = 1, Male = 2
  - A = 1, B = 2, AB = 3, O = 4
- Ordinal data
  - Ordered
  - Often = 1, Sometimes = 2, Rarely = 3, Never = 4
  - First place = 1, Second place = 2, Third place = 3
:::

## Numeric data

::: {.incremental}
- Discrete data
  - Countable, integers
  - Number of children
  - Number of infected
- Continuous data
  - Uncountable
  - Height
  - Blood pressure
:::


## Sources of quantitiative data
- Interviews or surveys
- Employment records
- Medical records
- Death certificates
- Institutions or agencies

# Measures

## Ratios
- Measure of relative magnitude of two quantities
- How many times is quantity 1 larger compared to quantity 2
- Example: Death-to-case ratio, odds, and odds ratios

$$\text{ratio} = \frac{\text{quantity 1}}{\text{quantity 2}}$$

## Proportions
- Numerator is included in the denominator
- What fraction is affected
- Range: $\{0 ,1\}$ 
- Example: Attack rate

$$\text{proportion} = \frac{\text{subgroup}}{\text{whole}}$$

## Rates
- Change in population during specific period of time
- How quickly is an event occurring
- Examples: Incidence rate

$$\text{rate} = \frac{\text{number of events}}{\text{population}\times \text{time}}$$

## Population and sampling

:::{.incremental}
- Interest in population level quantities 
- Constraint: Money, time
- Solution: Statistics 
- Infer from sample to study population to target population
- Goal: Sample and study population should be representative 
:::

# Descriptive statistics

## Summary statistics
:::{.incremental}
- Describe measures for the observed sample
- Summarize and describe the empirical distribution
- Measure of center of the distribution
- Measure of spread of the distribution
:::

## Mean
- Measure of central tendency (center)
- Sensitive to outliers
- Numeric data

:::{.fragment .fade-in}
$$\bar{X} = \frac{1}{N} \times \sum_{i=1}^N{x_i}$$
:::
:::{.fragment .fade-in-then-out}
```{.r}
mean(var)
```
:::
:::{.fragment .fade-in}
```{.r}
mean var
```
:::

## Median
- Measure of central tendency (center)
- Separates the bottom 50% of the data from the top 50% 
- Less sensitive to outliers
- Data needs to be ordinal or numeric

:::{.fragment .fade-in-then-out}
```{.r}
median(var)
```
:::
:::{.fragment .fade-in}
```{.r}
tabstat var, s(median)
```
:::

## Range
- Measure of spread of empirical distribution 
- Difference between maximum and minimum value

:::{.fragment .fade-in-then-out}
```{.r}
max(var) - min(var)
```
:::
:::{.fragment .fade-in}
```{.r}
tabstat var, statistics(range)
```
:::

## Quartiles

- Divide the sorted data into four equal parts
- $Q_1$: divides the bottom 25% of the data from the top 75%
- Median is the second quartile $Q_2$
- $Q_3$:divides the bottom 75% of the data from the top 25%
- The inter-quartile range is the range between the first and third quartile

:::{.fragment .fade-in-then-out}
```{.r}
quantile(var)
IQR(var)
```
:::
:::{.fragment .fade-in}
```{.r}
tabstat var, statistics(q)
tabstat var, statistics(iqr)
```
:::

## Variance
- Measure of spread around the mean
- Conveys additional information about observed distribution
- Weighted mean of the squares of the distance of each observed value to the sample mean

$$s=\sqrt{\dfrac{\sum (x-\overline{x})^{2}}{n-1}}$$

:::{.fragment .fade-in-then-out}
```{.r}
var(var)
```
:::
:::{.fragment .fade-in}
```{.r}
su var, detail
```
:::

## Z-Score
- Measure of standardized variance
- Ratio: The observed value of $x$ is $z$ standard deviations away from the mean
$$z = \frac{x-\bar{x}}{s}$$


:::{.fragment .fade-in-then-out}
```{.r}
(var-mean(var))/var(var)
```
:::
:::{.fragment .fade-in}
```{.r}
ssc install zscore
zscore var
```
:::

## Covariance and correlation
:::{.fragment .fade-in}
- Covariance: 
  - Measure of joint variability between two observed variables
  - Do variables deviate from the mean together?
:::
:::{.fragment .fade-in}
- Correlation: 
  - Covariance divided by the standard deviation
  - Unit independent
:::

## Covariance and correlation
<br>
<br>
<br>
<br>
:::{.fragment .fade-in-then-out}
```{.r}
cov(var1, var2)
cor(var1, var2)
```
:::
:::{.fragment .fade-in}
```{.r}
co var1 var2
corr var1 var2
```
:::

# Inferential statistics

## Generalization

:::{.fargment}
- Sample quantities
  - Sample mean
  - Sample (co-)variance
  - ...
:::

:::{.fragment .fade-in-then-out}
- Population
  - Sample size of $\geq 30$: sample means are approx. normally distributed
  - Population mean (point estimation)
  - Population (co-)variance 
:::

## Point estimation
:::{.incremental}
- Estimate population parameter based on sample statistic
- Difference due to sampling error
- Repeated sampling: Multiple sample statistics have a distribution called sampling distribution
- Standard deviation of a sampling distribution is the standard error
:::

## Confidence interval
- Range based on the sample statistic that includes the unknown population parameter with $\alpha$ level of confidence 
- Margin of error: Half of width of confidence interval, or: multiple of standard error
- $\text{sample statistic ± margin of error}$

:::{.fragment .fade-in-then-out}

$$(\bar{X}-1.96 \times \frac{\sigma}{\sqrt{n}},\bar{X}+1.96 \times \frac{\sigma}{\sqrt{n}} )$$
:::

:::{.fragment .fade-in-then-out}
- t-distribution if population variance is unknown

$$(\bar{X}-t_{n-1}^{\frac{0.05}{2}} \times \frac{s}{\sqrt{n}},\bar{X}+t_{n-1}^{\frac{0.05}{2}} \times \frac{s}{\sqrt{n}} )$$
:::

## Hypothesis testing 
:::{.incremental}
- 
- 
:::

# Regression
## Background
:::{.incremental}
- Aim: 
  - Summary
  - Prediction
  - Explanation
- X: Independent variable
- Y: Dependent variable
:::

# Linear regression

## Estimation
- Ordinary least squares (OLS)

## Assumptions
- Linear function
- Equal variances of errors
- Independent errors
- Normally distributed errors

## Implementation

:::{.fragment .fade-in-then-out}
```{.r}
ols <- lm(Y ~ X, data)
summary(ols)
```
:::
:::{.fragment .fade-in}
```{.r}
reg y x 
```
:::

## Interpretation

# Logistic regression

## Estimation
- Likelihood vs probability
- What parameters maximize the likelihood function?
  - Hence: Maximum likelihood

## Assumptions

## Implementation

:::{.fragment .fade-in-then-out}
```{.r}
glm(Y ~ X, family=binomial(link="logit"))
```
:::
:::{.fragment .fade-in}
```{.r}
logit y x 
```
:::

## Interpretation

# Proportional odds regression

## Estimation
- Ordered dependent variables
- What parameters maximize the likelihood function?
  - Hence: Maximum likelihood

## Assumptions

## Implementation

:::{.fragment .fade-in-then-out}
```{.r}
VGAM:::vglm(as.factor(Y) ~ X, data, cumulative(parallel=TRUE, reverse=TRUE))
VGAM:::vglm(as.factor(Y) ~ X, data, propodds(reverse = TRUE))

```
:::

:::{.fragment .fade-in}
```{.r}
ologit y x 
```
:::

## Interpretation
- Output presented as odds ratios
- Marginal effects
:::{.fragment .fade-in-then-out}
```{.r}


```
:::
:::{.fragment .fade-in}
```{.r}
ologit y x 
```
:::
# Recap

## Exercises

Using the statistical software of your choosing, 

(@) Calculate the ratio of female to male participants 
(@) Calculate the fever prevalence
(@) Create a ladder plot of 

